// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxyT_0GSFYmRn1DxFQTAnNkJc007rm9ug',
    appId: '1:367763030973:web:d11c0bde3e06affae388d4',
    messagingSenderId: '367763030973',
    projectId: 'lenskartclone-287ed',
    authDomain: 'lenskartclone-287ed.firebaseapp.com',
    storageBucket: 'lenskartclone-287ed.appspot.com',
    measurementId: 'G-XJ4B8D3713',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArgON8hJwo2oJWcSvTVJKLJ1yLiGh2Du4',
    appId: '1:367763030973:android:a70a795fe081c3cae388d4',
    messagingSenderId: '367763030973',
    projectId: 'lenskartclone-287ed',
    storageBucket: 'lenskartclone-287ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfN-X6umJOP3PtpZYnL50PeOXsgL4nwtY',
    appId: '1:367763030973:ios:0cf771519425b222e388d4',
    messagingSenderId: '367763030973',
    projectId: 'lenskartclone-287ed',
    storageBucket: 'lenskartclone-287ed.appspot.com',
    iosBundleId: 'com.example.lenskartClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfN-X6umJOP3PtpZYnL50PeOXsgL4nwtY',
    appId: '1:367763030973:ios:0cf771519425b222e388d4',
    messagingSenderId: '367763030973',
    projectId: 'lenskartclone-287ed',
    storageBucket: 'lenskartclone-287ed.appspot.com',
    iosBundleId: 'com.example.lenskartClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxyT_0GSFYmRn1DxFQTAnNkJc007rm9ug',
    appId: '1:367763030973:web:e1d7b9a5d7910cd4e388d4',
    messagingSenderId: '367763030973',
    projectId: 'lenskartclone-287ed',
    authDomain: 'lenskartclone-287ed.firebaseapp.com',
    storageBucket: 'lenskartclone-287ed.appspot.com',
    measurementId: 'G-YPB86QC7S3',
  );
}
